version: "3.8"

services:
  testDb:
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:14-alpine
    ports:
      - 5433:5432
    restart: always
